### ISSUE TITLE
link to Google sheet in 3.6 Tables is not accessible

### ISSUE THREAD

**Issue by YanyanR** [brownplt/pyret-docs#23] opened 2017-09-10 21:47 UTC
The Google sheet ID used in the example [here](https://github.com/brownplt/pyret-docs/blob/352b50237eec75f0dc6e9c3ee197524a277ad6dd/src/builtin/tables.scrbl#L169) is not accessible, and causes error `No Spreadsheet with id "1BAexzf08Q5o8bXb_k8PwuE3tMKezxRfbKBKT-4L6UzI" found` in Pyret.

**Comment by jswrenn** [comment] 2017-09-26 18:09
The issue is that [this spreadsheet](https://docs.google.com/spreadsheets/d/1BAexzf08Q5o8bXb_k8PwuE3tMKezxRfbKBKT-4L6UzI/edit?usp=sharing) is not publicly viewable.

I believe the reference to this sheet was introduced by @tom-hoffman in 715e538dca9c0f1ec59ef09ff16bd28938354f40. Tom, do you own this sheet? If so, could you correct the permissions?

**Comment by tom-hoffman** [comment] 2017-09-27 19:34
I made it world-readable.

**Comment by schanzer** [comment] 2018-01-21 14:50
Since the file is now readable, the issue is fixed. Closing.

**Closed by schanzer** 2018-01-21 14:50 UTC
